import type { TimelineEvent } from "../timelineTypes";

export const TIMELINE_EVENTS_01: TimelineEvent[] = [
  {
    id: "e001",
    era: "taichang",
    dateLabel: "泰昌元年 九月（1620）",
    year: 1620,
    category: "jitong",
    title: "光宗骤崩，熹宗继统",
    summary:
      "光宗朱常洛即位仅二十九日驾崩；十六岁皇长子朱由校三让而后即皇帝位，改明年为天启元年，颁大赦。",
    characters: ["朱常洛", "朱由校", "杨涟", "方从哲"],
    source: "故事1",
  },
  {
    id: "e002",
    era: "taichang",
    dateLabel: "泰昌元年 九月（1620）",
    year: 1620,
    category: "dangzheng",
    title: "移宫案：乾清宫之争",
    summary:
      "先帝选侍李氏据乾清宫不退，杨涟、左光斗等力请移宫；皇上登极还正乾清宫，选侍移居哕鸾宫。",
    characters: ["李选侍", "杨涟", "左光斗", "王安", "魏进忠"],
    source: "故事1",
  },
  {
    id: "e003",
    era: "taichang",
    dateLabel: "泰昌元年 九月（1620）",
    year: 1620,
    category: "dangzheng",
    title: "红丸案：服红丸暴死引发党争",
    summary:
      "1620年，泰昌帝朱常洛登基仅29天就死了，事情发生在皇宫里。此前郑贵妃送来八名美女，皇帝身体本已非常虚弱；郑贵妃的亲信太监崔文昇又给他吃了泻药，病情进一步加重。后来鸿胪寺丞李可灼进献所谓的「仙丹」红丸——这种药药性极猛，据说含有铅、处女经血、人乳、辰砂等成分，其实是一种大补春药。皇帝吃了第一丸后稍有好转，但再服第二丸，次日凌晨就突然驾崩了。内阁首辅方从哲被指授意献药，对涉事者的处理也过宽。案件背后疑点指向郑贵妃可能为了保住地位而谋害新帝，引发激烈朝堂党争，最终以李可灼、崔文昇被流放结案，但真相至今仍是历史疑案。",
    characters: [
      "朱常洛",
      "李可灼",
      "郑贵妃",
      "崔文昇",
      "方从哲",
      "孙慎行",
    ],
    source: "故事1",
  },
  {
    id: "e004",
    era: "taichang",
    dateLabel: "泰昌元年 十月（1620）",
    year: 1620,
    category: "liaodong",
    title: "辽东经略更易：袁应泰代熊廷弼",
    summary:
      "熊廷弼屡与言官冲突被罢，袁应泰代为辽东经略，议进复抚顺、清河；杨镐、李如柏以丧师论罪。",
    characters: ["熊廷弼", "袁应泰", "杨镐", "李如柏"],
    source: "故事1",
  },
  {
    id: "e005",
    era: "tianqi",
    dateLabel: "天启元年（1621）",
    year: 1621,
    category: "yanhuan",
    title: "客氏、魏进忠受宠",
    summary:
      "乳母客氏封奉圣夫人，子侯国兴授锦衣千户；魏进忠（魏忠贤）照旧供职、提督宝和店，内廷恩宠渐著。",
    characters: ["客氏", "魏忠贤", "侯国兴"],
    source: "故事1",
  },
  {
    id: "e006",
    era: "tianqi",
    dateLabel: "天启元年 三月（1621）",
    year: 1621,
    category: "liaodong",
    title: "沈阳、辽阳连陷，袁应泰自焚",
    summary:
      "后金破沈阳，尤世功、贺世贤战死，浑河血战全军覆没；辽阳陷，经略袁应泰自焚，张铨骂贼缢死。",
    characters: ["袁应泰", "贺世贤", "尤世功", "张铨", "秦邦屏", "陈策"],
    source: "故事1",
  },
  {
    id: "e007",
    era: "tianqi",
    dateLabel: "天启元年 四月（1621）",
    year: 1621,
    category: "jitong",
    title: "天启帝大婚，册张皇后",
    summary: "册河南祥符张氏为皇后；张氏父张国纪封都督同知。",
    characters: ["张嫣", "张国纪"],
    source: "故事1",
  },
  {
    id: "e008",
    era: "tianqi",
    dateLabel: "天启元年 六月（1621）",
    year: 1621,
    category: "liaodong",
    title: "熊廷弼再起经略，三方布置",
    summary:
      "熊廷弼起为兵部尚书、经略辽东，提三方布置；王化贞巡抚广宁，主联虏制奴，经抚分歧自此始。",
    characters: ["熊廷弼", "王化贞", "王在晋"],
    source: "故事1",
  },
  {
    id: "e009",
    era: "tianqi",
    dateLabel: "天启元年 八月（1621）",
    year: 1621,
    category: "haifang",
    title: "毛文龙夜袭收复镇江（镇江奇捷）",
    summary:
      "王化贞遣毛文龙率二百余人夜渡鸭绿江，内应陈良策，擒伪游击佟养真父子，南卫震动；升毛文龙副总兵。",
    characters: ["毛文龙", "陈良策", "佟养真", "王化贞"],
    source: "故事1",
  },
  {
    id: "e010",
    era: "tianqi",
    dateLabel: "天启元年 九月（1621）",
    year: 1621,
    category: "xinan",
    title: "奢崇明重庆作乱（奢安之乱起）",
    summary:
      "奢崇明、子奢寅于重庆教场作乱，杀巡抚徐可求，据城伪号大梁，分兵逼成都；兴文知县张振德阖室殉节。",
    characters: ["奢崇明", "奢寅", "徐可求", "张振德"],
    source: "故事1",
  },
];
